

export const message = {
    idNotFoundMessage: "Please provide valid id'",
    userNotFoundMessage: "User not found",
    userExistsMessage: "User already exists",
    usernameExistsMessage: "Username already exists",
    userAlreadyVerifiedMessage: "User already verified",
    otpAttemptsExceededMessage: "Too many attempts. Please try again later",
    otpNotFoundMessage: "Please provide otp",
    invalidOtpMessage: "Invalid otp",
    otpExpiredMessage: "OTP expired. Generate new otp",
    loginSuccessfulMessage: "Login successful",
    userVerifiedMessage: "User verified successfully",
    otpSendMessage: "Otp sent successfully",
    missingFieldsMessage: "Please provide all required fields",
    loginLockedMessage: "Login attempts exceeded. Please try again later",
    badAuthMessage: "Invalid email or password",
    unAuthenticatedMessage: "Please login to continue",
    unAuthorizedMessage: "Unauthorized to perform this action ",
    logoutMessage: "Logged out successfully",
    userProfileFoundMessage: "User profile found",
    userProfileUpdatedMessage: "User profile updated successfully",
    userNotVerifiedMessage: "User not verified. Please verify your email",
    imageMissingMessage: "Please provide image",
    postCreatedMessage: "Post created successfully",
    postNotFoundMessage: "Post not found",
    postsFoundMessage: "All Posts fetched successfully",
    postFoundMessage: "Post fetched successfully",
    postDeletedMessage: "Post deleted successfully",
    usersFoundMessage: "All users fetched successfully",
    userFoundMessage: "User fetched successfully",
    userFollowedMessage: "User followed successfully",
    userAlreadyFollowedMessage: "User already followed",
    userUnfollowedMessage: "User unfollowed successfully",
    userNotFollowedMessage: "User not followed",
    postUnlikedMessage: "Post unliked successfully",
    postLikedMessage: "Post liked successfully",
    passwordNotFoundMessage: "Please provide password",
    passwordNotMatchMessage: "Password does not match",
    samePasswordMessage: "New password cannot be same as old password",
    passwordUpdatedMessage: "Password updated successfully",
    postUnsavedMessage: "Post unsaved successfully",
    postSavedMessage: "Post saved successfully",
    queryNotFoundMessage: "Query not found",
    chatFoundMessage: "Chat found successfully",
    chatsFoundMessage: "All Chats fetched successfully",
    messageSentMessage: "Message sent successfully",
    messagesFoundMessage: "All Messages fetched successfully",
    commentNotFoundMessage: "Comment not found",
    commentAddedMessage: "Comment added successfully",
    commentUpdatedMessage: "Comment updated successfully",
    commentDeletedMessage: "Comment deleted successfully",
    replyAddedMessage: "Reply added successfully",
    replyNotFoundMessage: "Reply not found",
    replyUpdatedMessage: "Reply updated successfully",
    replyDeletedMessage: "Reply deleted successfully",
    commentUnlikedMessage: "Comment unliked successfully",
    commentLikedMessage: "Comment liked successfully",
    replyUnlikedMessage: "Reply unliked successfully",
    replyLikedMessage: "Reply liked successfully",
    postUpdatedMessage: "Post updated successfully",
    notificationsFoundMessage: "All Notifications fetched successfully",
}